### ISSUE TITLE
web-ui file not found

### ISSUE THREAD

**Issue by ioweb-gr** [NoiseByNorthwest/php-spx#115] opened 2020-02-29 11:25 UTC
I found this project very interesting and wanted to try it but I seem to be doing something wrong. 
I'm trying to setup the extension but there seems to be a step missing from the readme. 

So far 

- I've installed the extension, 
- I can see it in my phpinfo screen and 
- I've adjusted the variables for my IP. 

![image](https://user-images.githubusercontent.com/20220341/75606366-8a7a1c80-5af4-11ea-84d3-270b3e0dc413.png)

Aftewards I try to visit my web url like this 

https://www.example.com/info.php?SPX_KEY=dev&SPX_UI_URI=/

And I receive the message

`File not found.`

![image](https://user-images.githubusercontent.com/20220341/75606374-b5647080-5af4-11ea-9199-3b33676d9d0e.png)

What's the next step to make the web-ui accessible?

**Comment by NoiseByNorthwest** [comment] 2020-03-01 22:51
Can you try with the https://github.com/NoiseByNorthwest/php-spx/tree/debug_logs branch ? It adds some useful logs. Especially the one starting with `debug local_file_name =` which will show you the resolved file to serve `SPX_UI_URI=/`.

**Comment by ioweb-gr** [comment] 2020-03-02 07:41
OK I cloned the directory and installed the extension as per the instructions 

phpize
./configure
make
sudo make install

The extension was installed however the result is the same as before. Where would I see the logs?

**Comment by ioweb-gr** [comment] 2020-03-02 08:06
Actually by reading the code I determined that it reads the error_log variables to determine what to show so I enabled every error logging in PHP. Now I see this

```
( ! ) Notice: SPX: debug /root/php-spx/php-spx-debug_logs/src/php_spx.c:http_ui_handler_shutdown():776 in Unknown on line 0
( ! ) Notice: SPX: debug local_file_name = /root/.phpbrew/php/phpbrew7_2_26_fdev/share/misc/php-spx/assets/web-ui/index.html in Unknown on line 0
( ! ) Notice: SPX: debug /root/php-spx/php-spx-debug_logs/src/php_spx.c:http_ui_handler_shutdown():812 in Unknown on line 0
( ! ) Notice: SPX: debug /root/php-spx/php-spx-debug_logs/src/php_spx.c:http_ui_handler_shutdown():815 in Unknown on line 0
( ! ) Warning: Cannot modify header information - headers already sent in Unknown on line 0
( ! ) Warning: Cannot modify header information - headers already sent in Unknown on line 0
File not found.
( ! ) Notice: SPX: debug /root/php-spx/php-spx-debug_logs/src/php_spx.c:http_ui_handler_shutdown():823 in Unknown on line 0
```

**Comment by NoiseByNorthwest** [comment] 2020-03-02 22:03
Thanks, it greatly helps.
I see at least 2 issues:
- the `/root/.phpbrew/php/phpbrew7_2_26_fdev/share/misc/php-spx/assets/web-ui/index.html` does not exists or cannot be read by SPX -> can you check if it exists and its permission bits ?
- the headers are already sent -> when you get a `File not found.` response, what is its HTTP status code ?

**Comment by ioweb-gr** [comment] 2020-03-03 09:34
Hopefully we'll get to the bottom of it :)

I'm responding below to your questions


### FILE
>     * the `/root/.phpbrew/php/phpbrew7_2_26_fdev/share/misc/php-spx/assets/web-ui/index.html` does not exists or cannot be read by SPX -> can you check if it exists and its permission bits ?

The file exists and it's 644 as all files but it's owned by root. It's expected to be owned by root since I had to compile the extension and install it as root.

```bash
~$ ll /root/.phpbrew/php/phpbrew7_2_26_fdev/share/misc/php-spx/assets/web-ui/index.html -h

-rw-r--r-- 1 root root 15K Mar  2 09:31 /root/.phpbrew/php/phpbrew7_2_26_fdev/share/misc/php-spx/assets/web-ui/index.html
```
 

### Response
>     * the headers are already sent -> when you get a `File not found.` response, what is its HTTP status code ?



The response seems to be 200. I'm posting the results below (I changed only the domain name)

```
Request URL:https://example.com/info.php?SPX_KEY=dev&SPX_UI_URI=/
Request Method:GET
Remote Address:164.68.99.99:443
Status Code:
200
Version:HTTP/2
```

### Response headers

```
HTTP/2 200 OK
server: nginx
date: Tue, 03 Mar 2020 09:29:43 GMT
content-type: text/html; charset=UTF-8
content-length: 470
x-powered-by: PHP/7.2.26
vary: Accept-Encoding
content-encoding: gzip
x-ua-compatible: IE=edge
x-powered-by: PleskLin
X-Firefox-Spdy: h2
```

### Request headers 

```
Host: example.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Cookie: AMCV_8F99160E571FC0427F000101%40AdobeOrg=1585540135%7CMCIDTS%7C18322%7CMCMID%7C59430576983439612983866684097899048131%7CMCOPTOUT-1583008893s%7CNONE%7CvVersion%7C4.4.0; private_content_version=updated-5e58a6aae22746.10977461; mage-translation-storage=%7B%7D; mage-translation-file-version=%7B%7D; tm-newsletter-popup=4; AMCVS_8F99160E571FC0427F000101%40AdobeOrg=1; s_cc=true; s_sq=%5B%5BB%5D%5D; form_key=qB39Pz2tw5L46ck9; XDEBUG_SESSION=phpstorm; SPX_KEY=dev
Upgrade-Insecure-Requests: 1
Pragma: no-cache
Cache-Control: no-cache
```

**Comment by NoiseByNorthwest** [comment] 2020-03-04 22:15
About the file, this is weird, I've no idea.
```
Notice: SPX: debug /root/php-spx/php-spx-debug_logs/src/php_spx.c:http_ui_handler_shutdown():812 in Unknown on line 0
```
If you see this log that means that the `fopen("/root/.phpbrew/php/phpbrew7_2_26_fdev/share/misc/php-spx/assets/web-ui/index.html", "rb")` has failed.

Regarding the headers being already sent, the 200 status code confirms that. Can you give me more details on your stack ? A Dockerfile ?

**Comment by ioweb-gr** [comment] 2020-03-05 10:13
To be honest I was a bit eager to test it on almost real situations, so I installed it directly on a Development server we own that is using PLESK. As my ultimate goal I want to profile applications in real servers so I can get accurate measurements and help improve the websites so I found it very appealing to try. This environment is a very real example of a lot of webserver setups. 

### OS
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"

### Web server 
Nginx is used as a reverse proxy forwarding requests to Apache. 
nginx version: nginx/1.16.1
Apache/2.4.29 (Ubuntu)

### PHP
PHP is running as an fpm service. 
It was installed using phpbrew and then I went ahead and manually installed spx extension. 

If I can provide any other info let me know

---
As a further test I went and did the following but I don't know if it helps at all or if it's at all recommended.

### Docroot  
/var/www/vhosts/example.com/httpdocs/

Then I set this variable in php.ini
spx.http_ui_assets_dir="/var/www/vhosts/example.com/httpdocs/web-ui"

and copied the folder `root/.phpbrew/php/phpbrew7_2_26_fdev/share/misc/php-spx/assets/web-ui`  to the docroot to set the same permissions and owner as other files served under the docroot.

I then retried opening the URL and it provided some interesting results

![image](https://user-images.githubusercontent.com/20220341/75971095-efa98580-5ed9-11ea-8a16-87b6d688ebc7.png)

I was able to see a part of the interface but also a lot of console errors

```
The stylesheet https://m2electronics.iostore.gr/info.php?SPX_UI_URI=/css/main.css was loaded as CSS even though its MIME type, “text/html”, is not “text/css”. info.php
Loading module from “https://m2electronics.iostore.gr/info.php?SPX_UI_URI=/js/dataTable.js” was blocked because of a disallowed MIME type (“text/html”).
info.php
Loading failed for the module with source “https://m2electronics.iostore.gr/info.php?SPX_UI_URI=/js/dataTable.js”. info.php:62:1
Loading module from “https://m2electronics.iostore.gr/info.php?SPX_UI_URI=/js/utils.js” was blocked because of a disallowed MIME type (“text/html”).
info.php
Loading module from “https://m2electronics.iostore.gr/info.php?SPX_UI_URI=/js/fmt.js” was blocked because of a disallowed MIME type (“text/html”).
info.php
Loading failed for the module with source “https://m2electronics.iostore.gr/info.php?SPX_UI_URI=/js/utils.js”. info.php:63:1
Loading failed for the module with source “https://m2electronics.iostore.gr/info.php?SPX_UI_URI=/js/fmt.js”. info.php:64:1
Loading module from “https://m2electronics.iostore.gr/?SPX_UI_URI=/js/utils.js” was blocked because of a disallowed MIME type (“text/html”).
info.php
Loading failed for the module with source “https://m2electronics.iostore.gr/?SPX_UI_URI=/js/utils.js”. info.php:66:1
Loading module from “https://m2electronics.iostore.gr/?SPX_UI_URI=/js/dataTable.js” was blocked because of a disallowed MIME type (“text/html”).
info.php
Loading failed for the module with source “https://m2electronics.iostore.gr/?SPX_UI_URI=/js/dataTable.js”. info.php:66:1
Loading module from “https://m2electronics.iostore.gr/?SPX_UI_URI=/js/fmt.js” was blocked because of a disallowed MIME type (“text/html”).
info.php
Loading failed for the module with source “https://m2electronics.iostore.gr/?SPX_UI_URI=/js/fmt.js”.
```

I then tried opening one of the js  urls and saw this
![image](https://user-images.githubusercontent.com/20220341/75971609-b0c7ff80-5eda-11ea-9049-62bc063f6410.png)

**Comment by NoiseByNorthwest** [comment] 2020-03-05 21:46
This is because the response (200, text/html) has already been sent before SPX does sent its own response (the 2nd issue I've mentionned earlier).
Can you show me the output of your `phpinfo()` ?

**Comment by ioweb-gr** [comment] 2020-03-08 17:07
Sure here it is

[phpinfo.zip](https://github.com/NoiseByNorthwest/php-spx/files/4303548/phpinfo.zip)

**Comment by BafS** [comment] 2020-03-10 12:09
FI I had the same issue today but I completely forgot to run `sudo make install` after the last `make`. It did the trick.

**Comment by ioweb-gr** [comment] 2020-03-10 12:37
I did the whole procedure as root so I don't think it's a permission issue during installation

**Comment by NoiseByNorthwest** [comment] 2020-03-13 22:41
@ioweb-gr I'm wondering, is `Notice: SPX: debug /root/php-spx/php-spx-debug_logs/src/php_spx.c:http_ui_handler_shutdown():776 in Unknown on line 0` really the first log you see for a single hit ?

**Comment by NoiseByNorthwest** [comment] 2020-03-13 22:52
Ok I think I got it. Your `display_errors` is `on`, that's why you also see the logs within the output and that's why custom headers cannot be sent once a log is emitted. Just switch to `master` and it should be OK since the root issue (UI's assets directory readability) is solved.

**Comment by ioweb-gr** [comment] 2020-03-13 23:39
@NoiseByNorthwest Thank you very much for still trying to help. I think we got somewhere now :)

Regarding your initial question about the logs. 

I started with using the default directory for assets at where the make install put them which was in the php installation folder. 

In my php error log file I was not getting any information with the normal spx version besides the file not found message that I could see on the page. That's why I put `display_errors = on;` to give you the messages above and I left the setting there. 

Afterwards I installed the debug version which actually produces this error in the error log even if I remove the `display_errors = on` with the message `file not found` 

```
[Sat Mar 14 01:03:41.494532 2020] [proxy_fcgi:error] [pid 2887:tid 139915496544000] [client 84.254.15.33:48262] AH01071: Got error 'PHP message: PHP Notice:  SPX: debug /root/php-spx/php-spx-debug_logs/src/php_spx.c:http_ui_handler_init():762 in Unknown on line 0\nPHP message: PHP Notice:  SPX: debug /root/php-spx/php-spx-debug_logs/src/php_spx.c:http_ui_handler_shutdown():776 in Unknown on line 0\nPHP message: PHP Notice:  SPX: debug local_file_name = /root/.phpbrew/php/phpbrew7_2_26_fdev/share/misc/php-spx/assets/web-ui/index.html in Unknown on line 0\nPHP message: PHP Notice:  SPX: debug /root/php-spx/php-spx-debug_logs/src/php_spx.c:http_ui_handler_shutdown():812 in Unknown on line 0\nPHP message: PHP Notice:  SPX: debug /root/php-spx/php-spx-debug_logs/src/php_spx.c:http_ui_handler_shutdown():815 in Unknown on line 0\n', referer: https://example.com/info.php?SPX_KEY=dev&SPX_UI_URI=/
[Sat Mar 14 01:03:41.495011 2020] [proxy_fcgi:error] [pid 2887:tid 139915496544000] [client 84.254.15.33:48262] AH01071: Got error 'PHP message: PHP Notice:  SPX: debug /root/php-spx/php-spx-debug_logs/src/php_spx.c:http_ui_handler_shutdown():823 in Unknown on line 0\n', referer: https://example.com/info.php?SPX_KEY=dev&SPX_UI_URI=/

```

My latest attempt was to copy the assets files in the same docroot to try it which also gave the above error. 

However after turning off display_errors, it seems to produce a result now and the profiler seems to work which looks incredible. 

So basically now the only problem that remains is that I cannot use the original installation of the assets folder but I have to manually put them in other places to actually work. 

This has gotten me very curious so I tried copying around the assets folder in the file system. 

Let me point my results 

| ownership | assets path                                 | result         |
|-----------|---------------------------------------------|----------------|
| root      | /var/www/vhosts/example.com/httpdocs/web-ui | works          |
| root      | /var/www/vhosts/example.com/web-ui          | works          |
| root      | /var/www/vhosts/web-ui                      | works          |
| root      | /var/www/web-ui                             | works          |
| root      | /var/web-ui                                 | works          |
| root      | /web-ui                                     | works          |
| root      | /root/web-ui                                | file not found |
| root      | /opt/web-ui                                 | works          |

Comparing the folder settings I noticed that on a default server installation for debian 9 or ubuntu 18.04 the `/root` folder has `700` permissions while the others have `755`. 

Finally I was able to replicate the issue. If any parent folder in the folderpath has permissions other than `755` the `web-ui` folder cannot be loaded and causes `file not found` error

That's pretty strange though because the web-ui folder itself has the proper permissions. I have no idea why the parent folder permissions are even calculated in this case. 

I confirmed finally by creating the following structure at `/test/web-ui` 
If I issue `chmod 700 /test` -> file not found
If I issue `chmod 755 /test` -> works

Tried with an intermediate folder between too for example `/test/test/web-ui` and issuing `chmod XXX /test` and the behaviour was consistent

**Comment by NoiseByNorthwest** [comment] 2020-03-20 17:38
Thanks @ioweb-gr for your time too !

> That's pretty strange though because the web-ui folder itself has the proper permissions. I have no idea why the parent folder permissions are even calculated in this case.

This is the expected behavior, I mean to take into account the permission bits of the ancestors. Otherwise it would be scary from a sysadmin POV :) But on the other hand, it is very easy to forget this behavior for a non-sysadmin user and to spend time figuring out what happens.

Now that all is ok for you, can we close this issue ?

**Comment by ioweb-gr** [comment] 2020-03-20 18:09
Yes, sure you can close this issue now. I used a different prefix for installing php so it's working now.

**Closed** 2020-03-23 08:58 UTC
